version: 2.1
orbs:
  python: circleci/python@2
jobs:
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Start Flask App
          command: python main.py

workflows:
  build-and-deploy:
    jobs:
      - deploy
